[build]
  command = "bun run build"
  publish = "_site"

[dev]
  port = 8888

[[redirects]]
  from = "/api/listening"
  to = "/.netlify/functions/listening"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
